services:
  steam-deck-notifier:
    build: .
    container_name: steam-deck-notifier
    restart: unless-stopped
    environment:
      COUNTRY_CODE: ${COUNTRY_CODE}
      CHECK_INTERVAL: ${CHECK_INTERVAL}
      ENABLE_LOGS: ${ENABLE_LOGS}
      CSV_DIR: ${CSV_DIR}
      STATUS_FILE: ${STATUS_FILE}
      LOG_FILE: ${LOG_FILE}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    volumes:
      - steamdeck_data:/app/data
volumes:
  steamdeck_data:
