version: '3.8'

services:
  steam-deck-notifier:
    build: .
    container_name: steam-deck-notifier
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'
